on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Fetch Build Keyboards
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yaml2json
        run: python3 -m pip install remarshal
      - id: set-matrix
        run: |
          matrix=$(yaml2json build.yaml | jq -c .)
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/west.yml') }}

      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- -DZMK_CONFIG=${GITHUB_WORKSPACE}/config -DSHIELD=${{ matrix.shield }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          # 파일명을 수동으로 지정하지 않고 고정값으로 테스트합니다.
          name: firmware-${{ matrix.shield }}
          # 빌드 결과물이 생성되는 정확한 위치를 직접 지정합니다.
          path: build/zephyr/zmk.uf2
